name: push ecr image and register new aws batch definition

on:
  push:
    # # PRが閉じたタイミングで実行
    # types:
    #   - closed
    # # mainブランチのみを対象とする
    # branches:
    #   - main

env:
  ECR_AND_AWS_BATCH_ROLE: "arn:aws:iam::955263032402:role/lambda-hello-github-actions-ecr-role"
  AWS_BATCH_JOB_DEFINITION_NAME: "aws-batch-4"

jobs:
  ECRPushAndDeployToAwsBatch:
    runs-on: ubuntu-latest
    # `permissions` を設定しないと OIDC が使えないので注意
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      # AWS 認証
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: "us-west-1"
          role-to-assume: "arn:aws:iam::955263032402:role/lambda-hello-github-actions-ecr-role"

      # ECR ログイン
      - uses: aws-actions/amazon-ecr-login@v1
        id: login-ecr # outputs で参照するために id を設定

      # Docker イメージを build・push する
      - name: build and push docker image to ecr
        id: push-ecr
        env:
          # ECR レジストリを `aws-actions/amazon-ecr-login` アクションの `outputs.registry` から取得
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          # イメージを push する ECR リポジトリ名
          REPOSITORY: "aws-batch"
          # 任意のイメージタグ
          # 今回は Git のコミットハッシュにしておく
          IMAGE_TAG: ${{ github.sha }}
        shell: bash
        run: |
          docker build . --tag ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}
          docker push ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}
          echo "##[set-output name=image;]$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

      - name: Get current JobDefinition revision
        id: get-current-job-definition
        shell: bash
        run: |
          if [[ ! $(which aws) > /dev/null ]]; then
            apt-get update && apt-get install -y awscli
          fi

          REVISION=$(aws batch describe-job-definitions --job-definition-name aws-batch-4 --status ACTIVE --query "jobDefinitions[0].revision")

          echo "##[set-output name=revision;]$REVISION"
          echo "##[set-output name=job-definition;]JobDefinition"

      - name: Register new JobDefinition
        id: register-new-job-definition
        env:
          ROLE_ARN: ${{ env.ECR_AND_AWS_BATCH_ROLE }}
          ECR_IMAGE_NAME: ${{ steps.push-ecr.outputs.image }}
          JOB_DEFINITION_NAME: ${{ steps.get-current-job-definition.outputs.job-definition }}
        shell: bash
        run: |
          NEW_REVISION=$(aws batch register-job-definition \
            --job-definition-name $JOB_DEFINITION_NAME \
            --type container \
            --container-properties "{
              \"image\": \"$ECR_IMAGE_NAME\",
              \"vcpus\": 0.5,
              \"memory\": 512,
              \"jobRoleArn\": \"$ROLE_ARN\"
            }" \
            --query "revision")

          echo "##[set-output name=revision;]$NEW_REVISION"
