name: push ecr image

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  AWSBatchUpdate:
    runs-on: ubuntu-latest
    # `permissions` を設定しないと OIDC が使えないので注意
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      # AWS 認証
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: "us-west-1"
          role-to-assume: "arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ECR_ROLE }}"

      # ECR ログイン
      - uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr

      # Docker イメージを build・push する
      - name: build and push docker image to ecr
        id: push-ecr
        env:
          # ECR レジストリを `aws-actions/amazon-ecr-login` アクションの `outputs.registry` から取得
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}/aws-batch
          # 任意のイメージタグ
          COMMIT_HASH: ${{ github.sha }}
        shell: bash
        run: |
          docker build . --tag ${{ env.REGISTRY }}:latest
          docker tag ${{ env.REGISTRY }}:latest ${{ env.REGISTRY }}:${{ env.COMMIT_HASH }}
          docker tag ${{ env.REGISTRY }}:latest ${{ env.REGISTRY }}:latest
          docker push ${{ env.REGISTRY }}:${{ env.COMMIT_HASH }}
          docker push ${{ env.REGISTRY }}:latest
